"""user avatar url

Revision ID: 40bec7da9010
Revises: 159156da2bfa
Create Date: 2026-02-26 05:49:53.302862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bec7da9010'
down_revision = '159156da2bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
